spring:
  application:
    name: project

openai:
  api-key: ${OPENAI_TOKEN}
  assistant:
    name: ${ASSISTANT_NAME} #My Assistant
    model: gpt-4
    instructions: ${ASSISTANT_INSTRUCTIONS} # You are a sales assistant...

logging:
  level:
    org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE
